ARTIFACT_MARKDOWN = "01_鍏ㄩ噺鑴辨按搴曠.md"
ARTIFACT_TABLES = "02_鐮旀姤鍏ㄩ噺缁撴瀯鍖栨暟鎹?xlsx"
ARTIFACT_RAW_TABLES = "02A_研报原始表格资产.xlsx"
ARTIFACT_SUMMARY = "03_鎶曠爺缁撹绮惧崕.xlsx"
ARTIFACT_CLASSIFICATION = "04_琛ㄦ牸鍒嗙被缁撴灉.xlsx"
ARTIFACT_FINANCIALS = "05_鏍稿績璐㈠姟鎸囨爣鏍囧噯鍖?xlsx"
ARTIFACT_MERGE_DIAGNOSTICS = "06_pdfplumber_merge_diagnostics.xlsx"
ARTIFACT_SEGMENT_MAP = "07_table_segment_map.xlsx"
