from __future__ import annotations

import copy
from typing import Any, Dict, List


SCHEMA_VERSION = "343A.review_queue.v1"

REVIEWER_DECISIONS = [
    "CONFIRM",
    "CORRECT",
    "REJECT",
    "NEEDS_SOURCE_CHECK",
    "ESCALATE",
    "SKIP",
]


def _field(
    *,
    name: str,
    group: str,
    data_type: str,
    excel_requirement: str,
    argilla_requirement: str,
    future_ui_requirement: str,
    allowed_values: list[str] | None,
    nullable: bool,
    default_value: Any,
    description: str,
    example: Any,
    validation_rule: str,
) -> Dict[str, Any]:
    return {
        "name": name,
        "group": group,
        "data_type": data_type,
        "excel_requirement": excel_requirement,
        "argilla_requirement": argilla_requirement,
        "future_ui_requirement": future_ui_requirement,
        "allowed_values": list(allowed_values or []),
        "nullable": nullable,
        "default_value": default_value,
        "description": description,
        "example": example,
        "validation_rule": validation_rule,
    }


FIELD_SPECS: List[Dict[str, Any]] = [
    _field(
        name="queue_item_id",
        group="Identity",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_hidden_primary_key",
        allowed_values=None,
        nullable=False,
        default_value="system_generated",
        description="Stable primary key for one review queue item.",
        example="343a::queue::0001",
        validation_rule="must be unique and non-empty",
    ),
    _field(
        name="review_item_id",
        group="Identity",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_visible_secondary_id",
        allowed_values=None,
        nullable=False,
        default_value="source_review_item_id_or_placeholder",
        description="Upstream row or review item identifier.",
        example="342g::queue::0001",
        validation_rule="must be non-empty",
    ),
    _field(
        name="source_stage",
        group="Identity",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_filterable",
        allowed_values=["342P", "342Q", "342R", "342S", "SUMMARY_DERIVED"],
        nullable=False,
        default_value="342R",
        description="Stage that produced the current row context.",
        example="342R",
        validation_rule="must be one known upstream stage or SUMMARY_DERIVED",
    ),
    _field(
        name="source_commit_sha",
        group="Identity",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_hidden",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Best-known source commit SHA for traceability.",
        example="57a6fac6c3587a90e657cbe14126854c1fecb49e",
        validation_rule="empty or a git SHA string",
    ),
    _field(
        name="source_artifact_path",
        group="Identity",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_link",
        allowed_values=None,
        nullable=False,
        default_value="",
        description="Absolute path to the source workbook or artifact.",
        example=r"D:\_datefac\output\audit_labeled_export_candidate_package_342r\audit_labeled_export_candidate_package_342r.xlsx",
        validation_rule="must be non-empty path string",
    ),
    _field(
        name="source_artifact_sheet",
        group="Identity",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_link_context",
        allowed_values=None,
        nullable=False,
        default_value="03_EXPORT_CANDIDATES",
        description="Workbook sheet or logical source section for this item.",
        example="03_EXPORT_CANDIDATES",
        validation_rule="must be non-empty",
    ),
    _field(
        name="source_row_id",
        group="Identity",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_trace_ref",
        allowed_values=None,
        nullable=False,
        default_value="",
        description="Original row id from the upstream workbook or synthetic placeholder id.",
        example="342q::export_candidate::0001",
        validation_rule="must be non-empty",
    ),
    _field(
        name="source_detail_level",
        group="Identity",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_badge",
        allowed_values=["ROW_LEVEL", "SUMMARY_DERIVED"],
        nullable=False,
        default_value="ROW_LEVEL",
        description="Whether the sample comes from a concrete row or a summary-only placeholder.",
        example="ROW_LEVEL",
        validation_rule="must be ROW_LEVEL or SUMMARY_DERIVED",
    ),
    _field(
        name="source_pdf_id",
        group="Document/table provenance",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="required_if_available",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Stable PDF id from the benchmark corpus when available.",
        example="342b_pdf_002",
        validation_rule="empty or non-empty string",
    ),
    _field(
        name="source_pdf_path",
        group="Document/table provenance",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_link",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Optional absolute PDF path if already materialized in upstream artifacts.",
        example=r"D:\_datefac\input\pdfs\sample.pdf",
        validation_rule="empty or path string",
    ),
    _field(
        name="page_number",
        group="Document/table provenance",
        data_type="integer",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="required_if_available",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Zero- or one-based source page number as preserved by upstream artifacts.",
        example=0,
        validation_rule="empty or integer >= 0",
    ),
    _field(
        name="table_id",
        group="Document/table provenance",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_filterable",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Source table id when the candidate came from a table-first artifact.",
        example="342b_pdf_002_content_list_001",
        validation_rule="empty or non-empty string",
    ),
    _field(
        name="cell_id",
        group="Document/table provenance",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_filterable",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Source cell id for future cell-level review queue usage.",
        example="342f::cell::0001",
        validation_rule="empty or non-empty string",
    ),
    _field(
        name="bbox",
        group="Document/table provenance",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_overlay_anchor",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Serialized bounding box of the original evidence region.",
        example="[52, 763, 606, 898]",
        validation_rule="empty or serialized bbox text",
    ),
    _field(
        name="image_path",
        group="Document/table provenance",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_preview_link",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Optional image evidence path.",
        example=r"D:\_datefac\output\mineru\images\sample.jpg",
        validation_rule="empty or path string",
    ),
    _field(
        name="source_html_snippet",
        group="Document/table provenance",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="required_text",
        future_ui_requirement="required_detail_tab",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Short HTML evidence snippet or table snippet for reviewer context.",
        example="<table><tr><td>EPS</td><td>2024A</td><td>1.2</td></tr></table>",
        validation_rule="may be empty; if present should be text only, not a file path",
    ),
    _field(
        name="source_text_snippet",
        group="Document/table provenance",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_text",
        future_ui_requirement="optional_detail_tab",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Plain-text context note, warning, or backlog caveat for reviewers.",
        example="simulation only; requires later audit before client delivery",
        validation_rule="may be empty; if present should be non-binary text",
    ),
    _field(
        name="metric_candidate_raw",
        group="Candidate value",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_show_original",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Original raw metric name before standardization when available.",
        example="营业收入（百万元）",
        validation_rule="may be empty; if present must be text",
    ),
    _field(
        name="metric_standardized",
        group="Candidate value",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_primary_value",
        allowed_values=None,
        nullable=False,
        default_value="",
        description="Standardized metric candidate currently proposed for review.",
        example="EPS",
        validation_rule="must be non-empty for row-level items; placeholder rows may use BACKLOG_PLACEHOLDER",
    ),
    _field(
        name="year_standardized",
        group="Candidate value",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_primary_value",
        allowed_values=None,
        nullable=False,
        default_value="",
        description="Standardized year token proposed for review.",
        example="2024A",
        validation_rule="must be non-empty",
    ),
    _field(
        name="value_numeric",
        group="Candidate value",
        data_type="number",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_primary_value",
        allowed_values=None,
        nullable=False,
        default_value="",
        description="Numeric candidate value currently proposed for review.",
        example=1.2,
        validation_rule="must be numeric for row-level items; placeholders may use 0",
    ),
    _field(
        name="normalized_unit",
        group="Candidate value",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_primary_value",
        allowed_values=None,
        nullable=False,
        default_value="",
        description="Normalized unit proposed for review.",
        example="元",
        validation_rule="must be non-empty for row-level items",
    ),
    _field(
        name="original_metric_standardized",
        group="Candidate value",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_show_original",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Original standardized metric before a simulated correction, if any.",
        example="revenue_yoy",
        validation_rule="may be empty",
    ),
    _field(
        name="original_normalized_unit",
        group="Candidate value",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_show_original",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Original unit before a simulated correction, if any.",
        example="CNY100M",
        validation_rule="may be empty",
    ),
    _field(
        name="correction_pattern",
        group="Candidate value",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_badge",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Correction pattern already logged upstream for simulated corrected rows.",
        example="REVENUE_AMOUNT_NOT_YOY",
        validation_rule="may be empty",
    ),
    _field(
        name="correction_reason",
        group="Candidate value",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_detail_note",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Reason text for an upstream correction pattern when available.",
        example="use corrected row",
        validation_rule="may be empty",
    ),
    _field(
        name="data_trust_level",
        group="Trust/risk",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_badge",
        allowed_values=[
            "HUMAN_REVIEWED",
            "SIMULATED_DIRECT_ADOPTED",
            "SIMULATED_CORRECTION_ADOPTED",
            "SUMMARY_DERIVED",
        ],
        nullable=False,
        default_value="SUMMARY_DERIVED",
        description="Current trust label carried from 342R/342Q/342P or summary placeholder generation.",
        example="SIMULATED_DIRECT_ADOPTED",
        validation_rule="must be one known trust label",
    ),
    _field(
        name="audit_label",
        group="Trust/risk",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_badge",
        allowed_values=None,
        nullable=False,
        default_value="",
        description="Current audit label from the export candidate package.",
        example="AUDIT_LABEL_SIMULATED_DIRECT",
        validation_rule="must be non-empty",
    ),
    _field(
        name="preview_source_type",
        group="Trust/risk",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_filterable",
        allowed_values=["HUMAN_REVIEWED", "SIMULATED_DIRECT", "SIMULATED_CORRECTED", "SUMMARY_DERIVED"],
        nullable=False,
        default_value="SUMMARY_DERIVED",
        description="Preview source bucket carried from upstream preview packaging.",
        example="SIMULATED_DIRECT",
        validation_rule="must be one known source type",
    ),
    _field(
        name="risk_level",
        group="Trust/risk",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_badge",
        allowed_values=["LOW", "MEDIUM", "HIGH", "CRITICAL"],
        nullable=False,
        default_value="HIGH",
        description="Review risk level for queue routing.",
        example="HIGH",
        validation_rule="must be LOW, MEDIUM, HIGH, or CRITICAL",
    ),
    _field(
        name="risk_tags",
        group="Trust/risk",
        data_type="list[string]",
        excel_requirement="required_readonly_semicolon_joined",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_badge_list",
        allowed_values=None,
        nullable=False,
        default_value=[],
        description="Structured risk tags that explain why the row appears in the queue.",
        example=["LATER_AUDIT_REQUIRED", "SIMULATION_ONLY"],
        validation_rule="must serialize to a non-empty list for queued items",
    ),
    _field(
        name="queue_reason_code",
        group="Trust/risk",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_filterable",
        allowed_values=[
            "STILL_HUMAN_REQUIRED",
            "SIMULATED_REQUIRES_LATER_AUDIT",
            "SEVERE_COLLISION",
            "DUPLICATE_METRIC_YEAR_SOURCE",
            "LOW_CONFIDENCE",
            "UNIT_METRIC_MISMATCH",
            "YEAR_ALIGNMENT_RISK",
            "VALUE_OUTLIER",
            "NEW_TEMPLATE_OR_LAYOUT",
            "RANDOM_SPOT_CHECK",
            "REGRESSION_FAILURE",
            "BACKLOG_REVIEW",
        ],
        nullable=False,
        default_value="BACKLOG_REVIEW",
        description="Primary routing reason for the review queue item.",
        example="SIMULATED_REQUIRES_LATER_AUDIT",
        validation_rule="must be one supported reason code",
    ),
    _field(
        name="confidence_score",
        group="Trust/risk",
        data_type="number",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_sort_key",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Optional numeric confidence carried from simulation or heuristics.",
        example=0.97,
        validation_rule="empty or numeric between 0 and 1",
    ),
    _field(
        name="collision_group_id",
        group="Trust/risk",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_link_group",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Collision key or duplicate group id for high-risk review routing.",
        example="ROE||2024A||9.9||%||0||[52, 763, 606, 898]",
        validation_rule="may be empty",
    ),
    _field(
        name="requires_disclaimer",
        group="Trust/risk",
        data_type="boolean",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_badge",
        allowed_values=["true", "false"],
        nullable=False,
        default_value=False,
        description="Whether the row requires an explicit display disclaimer.",
        example=True,
        validation_rule="must be boolean",
    ),
    _field(
        name="requires_later_audit",
        group="Trust/risk",
        data_type="boolean",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_badge",
        allowed_values=["true", "false"],
        nullable=False,
        default_value=False,
        description="Whether the row remains in later-audit scope.",
        example=True,
        validation_rule="must be boolean",
    ),
    _field(
        name="formal_client_export_allowed",
        group="Trust/risk",
        data_type="boolean",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_hidden_safety_flag",
        allowed_values=["false"],
        nullable=False,
        default_value=False,
        description="Safety boundary flag that must remain false in 343A.",
        example=False,
        validation_rule="must always be false in 343A",
    ),
    _field(
        name="client_ready",
        group="Trust/risk",
        data_type="boolean",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_hidden_safety_flag",
        allowed_values=["false"],
        nullable=False,
        default_value=False,
        description="Safety boundary flag that must remain false in 343A.",
        example=False,
        validation_rule="must always be false in 343A",
    ),
    _field(
        name="production_ready",
        group="Trust/risk",
        data_type="boolean",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_hidden_safety_flag",
        allowed_values=["false"],
        nullable=False,
        default_value=False,
        description="Safety boundary flag that must remain false in 343A.",
        example=False,
        validation_rule="must always be false in 343A",
    ),
    _field(
        name="not_final_confirmation",
        group="Trust/risk",
        data_type="boolean",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_banner_flag",
        allowed_values=["true"],
        nullable=False,
        default_value=True,
        description="Reminder that these queue items are not final confirmations or official export approvals.",
        example=True,
        validation_rule="must always be true in 343A",
    ),
    _field(
        name="review_status",
        group="Review workflow",
        data_type="string",
        excel_requirement="required_editable_dropdown",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_status_chip",
        allowed_values=[
            "CREATED",
            "QUEUED",
            "ASSIGNED",
            "IN_REVIEW",
            "REVIEWED_CONFIRMED",
            "REVIEWED_CORRECTED",
            "REJECTED",
            "NEEDS_SOURCE_CHECK",
            "NEEDS_ESCALATION",
            "SKIPPED",
            "READY_FOR_APPLY_SIMULATION",
            "APPLIED_TO_SIDECAR_SIMULATION",
            "ARCHIVED",
        ],
        nullable=False,
        default_value="QUEUED",
        description="Current queue lifecycle status for the item.",
        example="QUEUED",
        validation_rule="must be one supported lifecycle status",
    ),
    _field(
        name="review_priority",
        group="Review workflow",
        data_type="string",
        excel_requirement="required_editable_dropdown",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_priority_chip",
        allowed_values=["P0_BLOCKER", "P1_HIGH_RISK", "P2_STANDARD_REVIEW", "P3_SPOT_CHECK", "P4_BACKLOG"],
        nullable=False,
        default_value="P2_STANDARD_REVIEW",
        description="Priority assigned to the queue item.",
        example="P1_HIGH_RISK",
        validation_rule="must be one supported priority level",
    ),
    _field(
        name="assigned_reviewer_id",
        group="Review workflow",
        data_type="string",
        excel_requirement="optional_editable",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_assignee_picker",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Reviewer assignment placeholder for pilot routing.",
        example="reviewer_a",
        validation_rule="may be empty",
    ),
    _field(
        name="reviewer_decision",
        group="Review workflow",
        data_type="string",
        excel_requirement="optional_editable_dropdown",
        argilla_requirement="optional_response",
        future_ui_requirement="required_action_button_set",
        allowed_values=REVIEWER_DECISIONS,
        nullable=True,
        default_value="",
        description="Future reviewer decision captured by Excel or UI round-trip.",
        example="CORRECT",
        validation_rule="empty or one supported reviewer decision",
    ),
    _field(
        name="reviewer_metric_standardized",
        group="Review workflow",
        data_type="string",
        excel_requirement="optional_editable",
        argilla_requirement="optional_response",
        future_ui_requirement="editable_if_correct",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Reviewer-corrected metric when decision is CORRECT.",
        example="revenue",
        validation_rule="required when reviewer_decision=CORRECT",
    ),
    _field(
        name="reviewer_year_standardized",
        group="Review workflow",
        data_type="string",
        excel_requirement="optional_editable",
        argilla_requirement="optional_response",
        future_ui_requirement="editable_if_correct",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Reviewer-corrected year when decision is CORRECT.",
        example="2025E",
        validation_rule="required when reviewer_decision=CORRECT and year changes",
    ),
    _field(
        name="reviewer_value_numeric",
        group="Review workflow",
        data_type="number",
        excel_requirement="optional_editable",
        argilla_requirement="optional_response",
        future_ui_requirement="editable_if_correct",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Reviewer-corrected numeric value when decision is CORRECT.",
        example=18.69,
        validation_rule="required when reviewer_decision=CORRECT and value changes",
    ),
    _field(
        name="reviewer_normalized_unit",
        group="Review workflow",
        data_type="string",
        excel_requirement="optional_editable",
        argilla_requirement="optional_response",
        future_ui_requirement="editable_if_correct",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Reviewer-corrected unit when decision is CORRECT.",
        example="CNY100M",
        validation_rule="required when reviewer_decision=CORRECT and unit changes",
    ),
    _field(
        name="reviewer_note",
        group="Review workflow",
        data_type="string",
        excel_requirement="optional_editable_textarea",
        argilla_requirement="optional_response",
        future_ui_requirement="optional_detail_note",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Free-text note from reviewer or triage operator.",
        example="keep row but verify year header on next pass",
        validation_rule="may be empty",
    ),
    _field(
        name="reviewed_at",
        group="Review workflow",
        data_type="datetime",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_audit_stamp",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Timestamp when a review decision is recorded.",
        example="2026-06-11T15:05:00+00:00",
        validation_rule="empty or ISO 8601 timestamp",
    ),
    _field(
        name="review_round",
        group="Review workflow",
        data_type="integer",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_badge",
        allowed_values=None,
        nullable=False,
        default_value=1,
        description="Review iteration number for future round-trip handling.",
        example=1,
        validation_rule="must be integer >= 1",
    ),
    _field(
        name="apply_allowed",
        group="Output/application control",
        data_type="boolean",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_hidden_safety_flag",
        allowed_values=["false"],
        nullable=False,
        default_value=False,
        description="343A queue items are not directly applicable to production outputs.",
        example=False,
        validation_rule="must always be false in 343A pilot",
    ),
    _field(
        name="apply_target",
        group="Output/application control",
        data_type="string",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_hidden_safety_flag",
        allowed_values=["SIDECAR_SIMULATION_ONLY"],
        nullable=False,
        default_value="SIDECAR_SIMULATION_ONLY",
        description="Future apply target, bounded to sidecar simulation only.",
        example="SIDECAR_SIMULATION_ONLY",
        validation_rule="must be SIDECAR_SIMULATION_ONLY",
    ),
    _field(
        name="applied_at",
        group="Output/application control",
        data_type="datetime",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_hidden",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Placeholder apply timestamp for future simulation-only flows.",
        example="",
        validation_rule="must stay empty until a future sidecar apply simulation exists",
    ),
    _field(
        name="applied_by",
        group="Output/application control",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_hidden",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Placeholder apply actor for future simulation-only flows.",
        example="",
        validation_rule="must stay empty until a future sidecar apply simulation exists",
    ),
    _field(
        name="apply_batch_id",
        group="Output/application control",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_hidden",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Placeholder apply batch id for future simulation-only flows.",
        example="",
        validation_rule="must stay empty until a future sidecar apply simulation exists",
    ),
    _field(
        name="no_write_back_required",
        group="Output/application control",
        data_type="boolean",
        excel_requirement="required_readonly",
        argilla_requirement="required_metadata",
        future_ui_requirement="required_hidden_safety_flag",
        allowed_values=["true"],
        nullable=False,
        default_value=True,
        description="No-write-back proof requirement for every queue item in this pilot.",
        example=True,
        validation_rule="must always be true",
    ),
    _field(
        name="audit_log_ref",
        group="Output/application control",
        data_type="string",
        excel_requirement="optional_readonly",
        argilla_requirement="optional_metadata",
        future_ui_requirement="optional_link_group",
        allowed_values=None,
        nullable=True,
        default_value="",
        description="Reference to collision, backlog, or queue audit context.",
        example="ROE||2024A||9.9||%||0||[52, 763, 606, 898]",
        validation_rule="may be empty",
    ),
]


STATUS_CATALOG = [
    {"status": "CREATED", "is_terminal": False, "description": "Item created but not yet routed into active review."},
    {"status": "QUEUED", "is_terminal": False, "description": "Item is in the queue and awaits assignment."},
    {"status": "ASSIGNED", "is_terminal": False, "description": "Item is assigned to a reviewer or review batch."},
    {"status": "IN_REVIEW", "is_terminal": False, "description": "Item is currently being reviewed."},
    {"status": "REVIEWED_CONFIRMED", "is_terminal": False, "description": "Reviewer confirmed the candidate and can route it to simulation."},
    {"status": "REVIEWED_CORRECTED", "is_terminal": False, "description": "Reviewer corrected the candidate and can route it to simulation."},
    {"status": "REJECTED", "is_terminal": False, "description": "Reviewer rejected the candidate."},
    {"status": "NEEDS_SOURCE_CHECK", "is_terminal": False, "description": "Reviewer needs upstream source/evidence re-check."},
    {"status": "NEEDS_ESCALATION", "is_terminal": False, "description": "Item needs escalation or policy review."},
    {"status": "SKIPPED", "is_terminal": False, "description": "Item was intentionally skipped in this round."},
    {"status": "READY_FOR_APPLY_SIMULATION", "is_terminal": False, "description": "Review result is ready for a future sidecar-only apply simulation."},
    {"status": "APPLIED_TO_SIDECAR_SIMULATION", "is_terminal": False, "description": "Result was applied only to a sidecar simulation package."},
    {"status": "ARCHIVED", "is_terminal": True, "description": "Item is closed and archived for audit history."},
]


LIFECYCLE_TRANSITIONS = [
    {"from_status": "CREATED", "to_status": "QUEUED", "rule": "Initial system routing completed."},
    {"from_status": "QUEUED", "to_status": "ASSIGNED", "rule": "Assigned to a reviewer or pilot batch."},
    {"from_status": "QUEUED", "to_status": "IN_REVIEW", "rule": "Self-serve review started without explicit assignment."},
    {"from_status": "ASSIGNED", "to_status": "IN_REVIEW", "rule": "Reviewer opened the item."},
    {"from_status": "ASSIGNED", "to_status": "QUEUED", "rule": "Assignment released back to queue."},
    {"from_status": "IN_REVIEW", "to_status": "REVIEWED_CONFIRMED", "rule": "Reviewer confirms candidate as-is."},
    {"from_status": "IN_REVIEW", "to_status": "REVIEWED_CORRECTED", "rule": "Reviewer corrects candidate fields."},
    {"from_status": "IN_REVIEW", "to_status": "REJECTED", "rule": "Reviewer rejects candidate."},
    {"from_status": "IN_REVIEW", "to_status": "NEEDS_SOURCE_CHECK", "rule": "Evidence or provenance is insufficient."},
    {"from_status": "IN_REVIEW", "to_status": "NEEDS_ESCALATION", "rule": "Policy or risk escalation required."},
    {"from_status": "IN_REVIEW", "to_status": "SKIPPED", "rule": "Reviewer intentionally skips for later."},
    {"from_status": "REVIEWED_CONFIRMED", "to_status": "READY_FOR_APPLY_SIMULATION", "rule": "Confirmed item may feed future sidecar simulation only."},
    {"from_status": "REVIEWED_CORRECTED", "to_status": "READY_FOR_APPLY_SIMULATION", "rule": "Corrected item may feed future sidecar simulation only."},
    {"from_status": "REJECTED", "to_status": "ARCHIVED", "rule": "Rejected item can be archived."},
    {"from_status": "SKIPPED", "to_status": "QUEUED", "rule": "Skipped item returns to queue in a later round."},
    {"from_status": "NEEDS_SOURCE_CHECK", "to_status": "QUEUED", "rule": "Source issue resolved and item re-queued."},
    {"from_status": "NEEDS_ESCALATION", "to_status": "QUEUED", "rule": "Escalation resolved and item re-queued."},
    {"from_status": "READY_FOR_APPLY_SIMULATION", "to_status": "APPLIED_TO_SIDECAR_SIMULATION", "rule": "Future sidecar-only simulation consumed the reviewed item."},
    {"from_status": "APPLIED_TO_SIDECAR_SIMULATION", "to_status": "ARCHIVED", "rule": "Historical audit state closed."},
]


REASON_CODES = [
    {"reason_code": "STILL_HUMAN_REQUIRED", "default_priority": "P1_HIGH_RISK", "description": "Upstream pipeline explicitly says human review remains required."},
    {"reason_code": "SIMULATED_REQUIRES_LATER_AUDIT", "default_priority": "P2_STANDARD_REVIEW", "description": "Simulated preview row can appear only with disclaimer and later audit."},
    {"reason_code": "SEVERE_COLLISION", "default_priority": "P0_BLOCKER", "description": "High-severity collision exists and should be triaged first."},
    {"reason_code": "DUPLICATE_METRIC_YEAR_SOURCE", "default_priority": "P1_HIGH_RISK", "description": "Duplicate metric-year-source evidence was logged upstream."},
    {"reason_code": "LOW_CONFIDENCE", "default_priority": "P1_HIGH_RISK", "description": "Low simulation confidence or weak evidence needs review."},
    {"reason_code": "UNIT_METRIC_MISMATCH", "default_priority": "P1_HIGH_RISK", "description": "Unit looks risky for the metric."},
    {"reason_code": "YEAR_ALIGNMENT_RISK", "default_priority": "P1_HIGH_RISK", "description": "Year alignment may be wrong or ambiguous."},
    {"reason_code": "VALUE_OUTLIER", "default_priority": "P1_HIGH_RISK", "description": "Value looks abnormal and should be checked."},
    {"reason_code": "NEW_TEMPLATE_OR_LAYOUT", "default_priority": "P2_STANDARD_REVIEW", "description": "New layout or table format needs human validation."},
    {"reason_code": "RANDOM_SPOT_CHECK", "default_priority": "P3_SPOT_CHECK", "description": "Human-reviewed or trusted rows can still enter spot-check queue."},
    {"reason_code": "REGRESSION_FAILURE", "default_priority": "P0_BLOCKER", "description": "Regression or validation failure forces immediate review."},
    {"reason_code": "BACKLOG_REVIEW", "default_priority": "P4_BACKLOG", "description": "Summary-only backlog placeholder for future expansion."},
]


PRIORITY_LEVELS = [
    {"priority": "P0_BLOCKER", "routing_rule": "Immediate triage before any broader pilot expansion.", "sla_hint": "same_day"},
    {"priority": "P1_HIGH_RISK", "routing_rule": "High-risk collision, source-check, or policy-sensitive row.", "sla_hint": "next_batch"},
    {"priority": "P2_STANDARD_REVIEW", "routing_rule": "Normal later-audit review row.", "sla_hint": "standard_queue"},
    {"priority": "P3_SPOT_CHECK", "routing_rule": "Spot-check or QA sample from already reviewed rows.", "sla_hint": "periodic"},
    {"priority": "P4_BACKLOG", "routing_rule": "Summary-derived backlog placeholder for planning, not immediate execution.", "sla_hint": "planning"},
]


TRUST_MAPPING = [
    {
        "data_trust_level": "HUMAN_REVIEWED",
        "review_queue_behavior": "may enter spot-check queue but still not a formal export row",
        "demo_display_rule": "can appear in demo/client preview context",
        "required_disclaimer_rule": "disclaimer optional, based on package warning",
        "later_audit_rule": "later audit optional, risk-driven",
    },
    {
        "data_trust_level": "SIMULATED_DIRECT_ADOPTED",
        "review_queue_behavior": "must enter later-audit capable queue before any broader use",
        "demo_display_rule": "demo-only with disclaimer",
        "required_disclaimer_rule": "disclaimer required",
        "later_audit_rule": "later audit required",
    },
    {
        "data_trust_level": "SIMULATED_CORRECTION_ADOPTED",
        "review_queue_behavior": "must enter later-audit capable queue before any broader use",
        "demo_display_rule": "demo-only with disclaimer",
        "required_disclaimer_rule": "disclaimer required",
        "later_audit_rule": "later audit required",
    },
    {
        "data_trust_level": "SUMMARY_DERIVED",
        "review_queue_behavior": "planning placeholder only, not a real review completion row",
        "demo_display_rule": "internal planning only",
        "required_disclaimer_rule": "n/a",
        "later_audit_rule": "expand into row-level queue later",
    },
]


def _clone(records: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    return copy.deepcopy(records)


def field_specs() -> List[Dict[str, Any]]:
    return _clone(FIELD_SPECS)


def status_catalog() -> List[Dict[str, Any]]:
    return _clone(STATUS_CATALOG)


def lifecycle_transitions() -> List[Dict[str, Any]]:
    return _clone(LIFECYCLE_TRANSITIONS)


def reason_codes() -> List[Dict[str, Any]]:
    return _clone(REASON_CODES)


def priority_levels() -> List[Dict[str, Any]]:
    return _clone(PRIORITY_LEVELS)


def trust_mapping() -> List[Dict[str, Any]]:
    return _clone(TRUST_MAPPING)


def field_count() -> int:
    return len(FIELD_SPECS)


def required_field_count() -> int:
    return sum(1 for spec in FIELD_SPECS if not spec["nullable"])


def status_count() -> int:
    return len(STATUS_CATALOG)


def reason_code_count() -> int:
    return len(REASON_CODES)


def priority_count() -> int:
    return len(PRIORITY_LEVELS)


def build_excel_template_spec() -> Dict[str, Any]:
    columns: List[Dict[str, Any]] = []
    editable_names = {
        "review_status",
        "review_priority",
        "assigned_reviewer_id",
        "reviewer_decision",
        "reviewer_metric_standardized",
        "reviewer_year_standardized",
        "reviewer_value_numeric",
        "reviewer_normalized_unit",
        "reviewer_note",
    }
    for spec in FIELD_SPECS:
        name = spec["name"]
        is_editable = name in editable_names
        columns.append(
            {
                "column_name": name,
                "group": spec["group"],
                "display_order": len(columns) + 1,
                "editable": is_editable,
                "required_in_template": not spec["nullable"] or is_editable,
                "excel_cell_mode": "editable" if is_editable else "readonly",
                "dropdown_values": spec["allowed_values"],
                "default_value": spec["default_value"],
                "validation_rule": spec["validation_rule"],
                "description": spec["description"],
            }
        )
    return {
        "schema_version": SCHEMA_VERSION,
        "sheet_name": "review_queue_roundtrip",
        "freeze_panes": "A2",
        "protected_readonly_columns": sorted(name for name in {spec["name"] for spec in FIELD_SPECS} - editable_names),
        "editable_columns": sorted(editable_names),
        "columns": columns,
    }


def build_argilla_mapping() -> Dict[str, Any]:
    return {
        "schema_version": SCHEMA_VERSION,
        "dataset_name": "datefac_review_queue_343a_pilot",
        "record_id_field": "queue_item_id",
        "text_fields": [
            {"argilla_field": "source_html_snippet", "queue_field": "source_html_snippet", "required": False},
            {"argilla_field": "source_text_snippet", "queue_field": "source_text_snippet", "required": False},
        ],
        "metadata_fields": [
            {"argilla_field": spec["name"], "queue_field": spec["name"], "data_type": spec["data_type"]}
            for spec in FIELD_SPECS
            if spec["name"] not in {"source_html_snippet", "source_text_snippet", "reviewer_note"}
        ],
        "response_fields": [
            {"argilla_field": "reviewer_decision", "queue_field": "reviewer_decision", "allowed_values": REVIEWER_DECISIONS},
            {"argilla_field": "reviewer_metric_standardized", "queue_field": "reviewer_metric_standardized"},
            {"argilla_field": "reviewer_year_standardized", "queue_field": "reviewer_year_standardized"},
            {"argilla_field": "reviewer_value_numeric", "queue_field": "reviewer_value_numeric"},
            {"argilla_field": "reviewer_normalized_unit", "queue_field": "reviewer_normalized_unit"},
            {"argilla_field": "reviewer_note", "queue_field": "reviewer_note"},
        ],
        "pluggable_interface_only": True,
        "sdk_called_in_343a": False,
    }


def build_ui_contract() -> Dict[str, Any]:
    return {
        "schema_version": SCHEMA_VERSION,
        "positioning": "Review Queue is the stable system contract; Argilla is only one pluggable review interface.",
        "list_view_columns": [
            "queue_item_id",
            "review_priority",
            "review_status",
            "data_trust_level",
            "queue_reason_code",
            "metric_standardized",
            "year_standardized",
            "value_numeric",
            "normalized_unit",
            "source_pdf_id",
            "page_number",
            "requires_disclaimer",
            "requires_later_audit",
        ],
        "detail_view_sections": [
            "identity_and_trace",
            "candidate_value",
            "risk_and_disclaimer",
            "evidence_html_or_text",
            "review_decision_form",
            "audit_log",
        ],
        "review_actions": REVIEWER_DECISIONS,
        "validation_rules": [
            "reviewer_decision must be one supported value",
            "CORRECT should populate at least one reviewer_* correction field",
            "formal_client_export_allowed must stay false",
            "client_ready must stay false",
            "production_ready must stay false",
            "apply_allowed must stay false in 343A",
        ],
        "export_contract": [
            "Excel round-trip must preserve queue_item_id and all readonly trace fields",
            "Argilla export must preserve metadata keys without mutating upstream workbooks",
            "Future UI must emit audit_log_ref and review timestamps",
        ],
        "audit_log_expectations": [
            "every status change should be traceable",
            "every correction should preserve original candidate fields",
            "no write-back to upstream workbooks is allowed in 343A",
        ],
    }


def _json_schema_for_field(spec: Dict[str, Any]) -> Dict[str, Any]:
    data_type = spec["data_type"]
    schema: Dict[str, Any]
    if data_type == "string":
        schema = {"type": "string"}
    elif data_type == "integer":
        schema = {"type": "integer"}
    elif data_type == "number":
        schema = {"type": "number"}
    elif data_type == "boolean":
        schema = {"type": "boolean"}
    elif data_type == "datetime":
        schema = {"type": "string", "format": "date-time"}
    elif data_type == "list[string]":
        schema = {"type": "array", "items": {"type": "string"}}
    else:
        schema = {"type": "string"}
    if spec["nullable"]:
        schema = {"anyOf": [schema, {"type": "null"}, {"type": "string", "maxLength": 0}]}
    if spec["allowed_values"]:
        if "anyOf" in schema:
            schema["anyOf"][0]["enum"] = spec["allowed_values"]
        else:
            schema["enum"] = spec["allowed_values"]
    schema["description"] = spec["description"]
    return schema


def build_json_schema() -> Dict[str, Any]:
    properties = {spec["name"]: _json_schema_for_field(spec) for spec in FIELD_SPECS}
    required = [spec["name"] for spec in FIELD_SPECS if not spec["nullable"]]
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "DateFac Review Queue Item 343A",
        "type": "object",
        "additionalProperties": False,
        "required": required,
        "properties": properties,
    }
